[package]
name = "flap"
version = "0.1.0"
edition = "2024"

[dependencies]
patina-cad = {workspace = true}
anyhow = "1.0.98"
tokio = {version="1.45.1",features = ["macros","rt-multi-thread","process"]}
