[workspace]
resolver = "3"
members = [ "examples/face", "examples/flap", "patina-3mf", "patina-bambu","patina-cad"]

[workspace.dependencies]
patina-cad = {path="patina-cad"}
patina-3mf = {path="patina-3mf"}
patina-bambu = {path = "patina-bambu"}