[package]
name = "patina-scalar"
version = "0.1.0"
edition = "2024"

[dependencies]
inari = {version="2.0.0",optional=true}
rand = "0.9.1"
ordered-float = "5.0.0"
itertools = "0.14.0"

[features]
inari = ["dep:inari"]