[package]
name = "patina-3mf"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
xml = "0.8.20"
serde-xml-rs = "0.8.1"
zip = "4.2.0"
anyhow = "1.0.98"
serde_json = "1.0.140"
serde_with = "3.13.0"